name: Build, Bundle, Release Go Plugin

on:
  push:
    branches: [ "gh-actions-buildplugin" ]
  pull_request:
    branches: [ "gh-actions-buildplugin" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Build Go Plugin
      run: make go-build
      
    - name: Bundle Go Plugin
      run: docker-compose run --rm --entrypoint "bundle/bundle-entrypoint.sh" tyk-gateway
      
    - name: Upload Bundle
      uses: actions/upload-artifact@v3
      with:
        name: customgoplugin.zip
        path: tyk/bundle/bundle.zip